Add a friendly message when GNU tar is not found (#288)

diff --git a/bin/test-build-on-all-distros b/bin/test-build-on-all-distros
--- a/bin/test-build-on-all-distros
+++ b/bin/test-build-on-all-distros
@@ -57,6 +57,13 @@ then
 else
   TAR=tar
 fi
+
+if ! [[ "$("$TAR" --version)" =~ GNU ]]
+then
+  echo 'GNU tar is required. (Install the gnu-tar package from Homebrew to fix it if you are using macOS)' >&2
+  exit 1
+fi
+
 (
   set -x
   cd "$SOURCE_DIR"
